### ISSUE TITLE
Regd. task definition

### ISSUE THREAD

**Issue by swapb94** [liangsusan-git/AV-NeRF#1]
Thank you for your amazing work. 
What is the difference between a_s and a*_s (Section 3)? Aren't these same?, the one that is included as "source_syn_re.wav" in each scene in the RWAS dataset.
Please check the attached screenshot.
![gaw](https://github.com/liangsusan-git/AV-NeRF/assets/26220501/73619b8a-8bdf-44b0-922f-3b0abe7f5fe5)

**Comment by liangsusan-git** [comment]
Hi,

Thanks for your interest in our work! You posed a good question.

a_s and a_s^* are different. a_s is used for training, while a_s^* is used for inference. Specifically, during training, the model accepts multiple observations O = {O_1, O_2, ... O_N}, where O_i = {p_i, a_s_i, a_t_i, I_i}. During inference, we feed the model with a new pose p^* and new audio a_s^*.

We have divided "source_syn_re.wav" into training and inference subsets. You can refer to "transforms_train.json" and "transforms_val.json" for more details.

**Comment by swapb94** [comment]
Many thanks! it is much clear now.
Also, any tentative date regarding code release?

**Comment by liangsusan-git** [comment]
I am glad it helps. I plan to release the code before Feb 15th. I know this is not ideal, but unfortunately, I can not set aside time to release my code now.
